// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chain_schema.proto

package chain_schema

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PrimitiveType int32

const (
	BOOL        PrimitiveType = 0
	INT3        PrimitiveType = 1
	INT64       PrimitiveType = 2
	UINT32      PrimitiveType = 3
	UINT64      PrimitiveType = 4
	SINT32      PrimitiveType = 5
	SINT64      PrimitiveType = 6
	FIXED32     PrimitiveType = 7
	FIXED64     PrimitiveType = 8
	SFIXED32    PrimitiveType = 9
	SFIXED64    PrimitiveType = 10
	STRING      PrimitiveType = 11
	BYTES       PrimitiveType = 12
	BIG_INTEGER PrimitiveType = 13
	BIG_DECIMAL PrimitiveType = 14
	DATETIME    PrimitiveType = 15
	DURATION    PrimitiveType = 16
	INTERVAL    PrimitiveType = 17
)

var PrimitiveType_name = map[int32]string{
	0:  "BOOL",
	1:  "INT3",
	2:  "INT64",
	3:  "UINT32",
	4:  "UINT64",
	5:  "SINT32",
	6:  "SINT64",
	7:  "FIXED32",
	8:  "FIXED64",
	9:  "SFIXED32",
	10: "SFIXED64",
	11: "STRING",
	12: "BYTES",
	13: "BIG_INTEGER",
	14: "BIG_DECIMAL",
	15: "DATETIME",
	16: "DURATION",
	17: "INTERVAL",
}

var PrimitiveType_value = map[string]int32{
	"BOOL":        0,
	"INT3":        1,
	"INT64":       2,
	"UINT32":      3,
	"UINT64":      4,
	"SINT32":      5,
	"SINT64":      6,
	"FIXED32":     7,
	"FIXED64":     8,
	"SFIXED32":    9,
	"SFIXED64":    10,
	"STRING":      11,
	"BYTES":       12,
	"BIG_INTEGER": 13,
	"BIG_DECIMAL": 14,
	"DATETIME":    15,
	"DURATION":    16,
	"INTERVAL":    17,
}

func (PrimitiveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{0}
}

type MethodType int32

const (
	TX    MethodType = 0
	QUERY MethodType = 1
	UTIL  MethodType = 2
)

var MethodType_name = map[int32]string{
	0: "TX",
	1: "QUERY",
	2: "UTIL",
}

var MethodType_value = map[string]int32{
	"TX":    0,
	"QUERY": 1,
	"UTIL":  2,
}

func (MethodType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{1}
}

type TypeRef struct {
	// Types that are valid to be assigned to Info:
	//	*TypeRef_Primitive
	//	*TypeRef_ComplexType
	//	*TypeRef_Array
	//	*TypeRef_Optional
	Info isTypeRef_Info `protobuf_oneof:"info"`
}

func (m *TypeRef) Reset()      { *m = TypeRef{} }
func (*TypeRef) ProtoMessage() {}
func (*TypeRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{0}
}
func (m *TypeRef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TypeRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TypeRef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TypeRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeRef.Merge(m, src)
}
func (m *TypeRef) XXX_Size() int {
	return m.Size()
}
func (m *TypeRef) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeRef.DiscardUnknown(m)
}

var xxx_messageInfo_TypeRef proto.InternalMessageInfo

type isTypeRef_Info interface {
	isTypeRef_Info()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type TypeRef_Primitive struct {
	Primitive PrimitiveType `protobuf:"varint,1,opt,name=primitive,proto3,enum=PrimitiveType,oneof" json:"primitive,omitempty"`
}
type TypeRef_ComplexType struct {
	ComplexType uint64 `protobuf:"varint,2,opt,name=complex_type,json=complexType,proto3,oneof" json:"complex_type,omitempty"`
}
type TypeRef_Array struct {
	Array *TypeRef `protobuf:"bytes,3,opt,name=array,proto3,oneof" json:"array,omitempty"`
}
type TypeRef_Optional struct {
	Optional *TypeRef `protobuf:"bytes,4,opt,name=optional,proto3,oneof" json:"optional,omitempty"`
}

func (*TypeRef_Primitive) isTypeRef_Info()   {}
func (*TypeRef_ComplexType) isTypeRef_Info() {}
func (*TypeRef_Array) isTypeRef_Info()       {}
func (*TypeRef_Optional) isTypeRef_Info()    {}

func (m *TypeRef) GetInfo() isTypeRef_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *TypeRef) GetPrimitive() PrimitiveType {
	if x, ok := m.GetInfo().(*TypeRef_Primitive); ok {
		return x.Primitive
	}
	return BOOL
}

func (m *TypeRef) GetComplexType() uint64 {
	if x, ok := m.GetInfo().(*TypeRef_ComplexType); ok {
		return x.ComplexType
	}
	return 0
}

func (m *TypeRef) GetArray() *TypeRef {
	if x, ok := m.GetInfo().(*TypeRef_Array); ok {
		return x.Array
	}
	return nil
}

func (m *TypeRef) GetOptional() *TypeRef {
	if x, ok := m.GetInfo().(*TypeRef_Optional); ok {
		return x.Optional
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypeRef) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypeRef_Primitive)(nil),
		(*TypeRef_ComplexType)(nil),
		(*TypeRef_Array)(nil),
		(*TypeRef_Optional)(nil),
	}
}

type ComplexType struct {
	Namespace uint64 `protobuf:"varint,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Info:
	//	*ComplexType_Struct
	//	*ComplexType_Enum
	//	*ComplexType_Interface
	Info isComplexType_Info `protobuf_oneof:"info"`
}

func (m *ComplexType) Reset()      { *m = ComplexType{} }
func (*ComplexType) ProtoMessage() {}
func (*ComplexType) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{1}
}
func (m *ComplexType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ComplexType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ComplexType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ComplexType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexType.Merge(m, src)
}
func (m *ComplexType) XXX_Size() int {
	return m.Size()
}
func (m *ComplexType) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexType.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexType proto.InternalMessageInfo

type isComplexType_Info interface {
	isComplexType_Info()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type ComplexType_Struct struct {
	Struct *Struct `protobuf:"bytes,3,opt,name=struct,proto3,oneof" json:"struct,omitempty"`
}
type ComplexType_Enum struct {
	Enum *Enum `protobuf:"bytes,4,opt,name=enum,proto3,oneof" json:"enum,omitempty"`
}
type ComplexType_Interface struct {
	Interface *Interface `protobuf:"bytes,5,opt,name=interface,proto3,oneof" json:"interface,omitempty"`
}

func (*ComplexType_Struct) isComplexType_Info()    {}
func (*ComplexType_Enum) isComplexType_Info()      {}
func (*ComplexType_Interface) isComplexType_Info() {}

func (m *ComplexType) GetInfo() isComplexType_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ComplexType) GetNamespace() uint64 {
	if m != nil {
		return m.Namespace
	}
	return 0
}

func (m *ComplexType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComplexType) GetStruct() *Struct {
	if x, ok := m.GetInfo().(*ComplexType_Struct); ok {
		return x.Struct
	}
	return nil
}

func (m *ComplexType) GetEnum() *Enum {
	if x, ok := m.GetInfo().(*ComplexType_Enum); ok {
		return x.Enum
	}
	return nil
}

func (m *ComplexType) GetInterface() *Interface {
	if x, ok := m.GetInfo().(*ComplexType_Interface); ok {
		return x.Interface
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ComplexType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ComplexType_Struct)(nil),
		(*ComplexType_Enum)(nil),
		(*ComplexType_Interface)(nil),
	}
}

type Struct struct {
	Fields []*Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (m *Struct) Reset()      { *m = Struct{} }
func (*Struct) ProtoMessage() {}
func (*Struct) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{2}
}
func (m *Struct) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Struct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Struct.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Struct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Struct.Merge(m, src)
}
func (m *Struct) XXX_Size() int {
	return m.Size()
}
func (m *Struct) XXX_DiscardUnknown() {
	xxx_messageInfo_Struct.DiscardUnknown(m)
}

var xxx_messageInfo_Struct proto.InternalMessageInfo

func (m *Struct) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Field struct {
	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type *TypeRef `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (m *Field) Reset()      { *m = Field{} }
func (*Field) ProtoMessage() {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{3}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Field.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return m.Size()
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetType() *TypeRef {
	if m != nil {
		return m.Type
	}
	return nil
}

type Enum struct {
	Values []*Value `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (m *Enum) Reset()      { *m = Enum{} }
func (*Enum) ProtoMessage() {}
func (*Enum) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{4}
}
func (m *Enum) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Enum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Enum.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Enum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enum.Merge(m, src)
}
func (m *Enum) XXX_Size() int {
	return m.Size()
}
func (m *Enum) XXX_DiscardUnknown() {
	xxx_messageInfo_Enum.DiscardUnknown(m)
}

var xxx_messageInfo_Enum proto.InternalMessageInfo

func (m *Enum) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type Value struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int32  `protobuf:"zigzag32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Value) Reset()      { *m = Value{} }
func (*Value) ProtoMessage() {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{5}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Value.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return m.Size()
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Interface struct {
	Implementers []uint64 `protobuf:"varint,1,rep,packed,name=implementers,proto3" json:"implementers,omitempty"`
}

func (m *Interface) Reset()      { *m = Interface{} }
func (*Interface) ProtoMessage() {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{6}
}
func (m *Interface) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}
func (m *Interface) XXX_Size() int {
	return m.Size()
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetImplementers() []uint64 {
	if m != nil {
		return m.Implementers
	}
	return nil
}

type Method struct {
	Type   MethodType `protobuf:"varint,1,opt,name=type,proto3,enum=MethodType" json:"type,omitempty"`
	Input  *TypeRef   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output *TypeRef   `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
}

func (m *Method) Reset()      { *m = Method{} }
func (*Method) ProtoMessage() {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{7}
}
func (m *Method) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Method.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return m.Size()
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetType() MethodType {
	if m != nil {
		return m.Type
	}
	return TX
}

func (m *Method) GetInput() *TypeRef {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Method) GetOutput() *TypeRef {
	if m != nil {
		return m.Output
	}
	return nil
}

type Table struct {
	Type *TypeRef `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (m *Table) Reset()      { *m = Table{} }
func (*Table) ProtoMessage() {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fbb4634437c5fc, []int{8}
}
func (m *Table) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Table.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return m.Size()
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetType() *TypeRef {
	if m != nil {
		return m.Type
	}
	return nil
}

func init() {
	proto.RegisterEnum("PrimitiveType", PrimitiveType_name, PrimitiveType_value)
	proto.RegisterEnum("MethodType", MethodType_name, MethodType_value)
	proto.RegisterType((*TypeRef)(nil), "TypeRef")
	proto.RegisterType((*ComplexType)(nil), "ComplexType")
	proto.RegisterType((*Struct)(nil), "Struct")
	proto.RegisterType((*Field)(nil), "Field")
	proto.RegisterType((*Enum)(nil), "Enum")
	proto.RegisterType((*Value)(nil), "Value")
	proto.RegisterType((*Interface)(nil), "Interface")
	proto.RegisterType((*Method)(nil), "Method")
	proto.RegisterType((*Table)(nil), "Table")
}

func init() { proto.RegisterFile("chain_schema.proto", fileDescriptor_87fbb4634437c5fc) }

var fileDescriptor_87fbb4634437c5fc = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x31, 0x4f, 0xdb, 0x4e,
	0x18, 0xc6, 0x7d, 0x89, 0xed, 0x24, 0xaf, 0x03, 0x1c, 0xa7, 0xff, 0x10, 0xe9, 0x8f, 0xae, 0xa9,
	0xab, 0xa2, 0x94, 0xc1, 0x55, 0x43, 0x14, 0xa9, 0x63, 0x02, 0x86, 0x58, 0x0a, 0xa1, 0xbd, 0x38,
	0x08, 0x26, 0x64, 0x82, 0x23, 0xac, 0x26, 0xb6, 0x95, 0x38, 0xa8, 0x6c, 0xfd, 0x08, 0xfd, 0x18,
	0x1d, 0x2b, 0xf5, 0x4b, 0x74, 0x64, 0x64, 0x2c, 0x66, 0xe9, 0xc8, 0xd6, 0xb5, 0xba, 0xb3, 0xe3,
	0x40, 0x61, 0x7b, 0x9f, 0xdf, 0xfb, 0xfa, 0x9e, 0xe7, 0xde, 0x9c, 0x02, 0x64, 0x78, 0xe1, 0x78,
	0xfe, 0xe9, 0x6c, 0x78, 0xe1, 0x4e, 0x1c, 0x23, 0x9c, 0x06, 0x51, 0xa0, 0x7f, 0x47, 0x50, 0xb0,
	0xaf, 0x42, 0x97, 0xb9, 0x23, 0x62, 0x40, 0x29, 0x9c, 0x7a, 0x13, 0x2f, 0xf2, 0x2e, 0xdd, 0x0a,
	0xaa, 0xa2, 0xda, 0x6a, 0x7d, 0xd5, 0xf8, 0xb0, 0x20, 0x7c, 0xaa, 0x23, 0xb1, 0xe5, 0x08, 0x79,
	0x05, 0xe5, 0x61, 0x30, 0x09, 0xc7, 0xee, 0xe7, 0xd3, 0xe8, 0x2a, 0x74, 0x2b, 0xb9, 0x2a, 0xaa,
	0xc9, 0x1d, 0x89, 0x69, 0x29, 0xe5, 0x5f, 0x90, 0x2a, 0x28, 0xce, 0x74, 0xea, 0x5c, 0x55, 0xf2,
	0x55, 0x54, 0xd3, 0xea, 0x45, 0x23, 0x75, 0xeb, 0x48, 0x2c, 0x69, 0x90, 0x4d, 0x28, 0x06, 0x61,
	0xe4, 0x05, 0xbe, 0x33, 0xae, 0xc8, 0x4f, 0x86, 0xb2, 0x5e, 0x5b, 0x05, 0xd9, 0xf3, 0x47, 0x81,
	0xfe, 0x03, 0x81, 0xb6, 0xf3, 0xc0, 0x61, 0x03, 0x4a, 0xbe, 0x33, 0x71, 0x67, 0xa1, 0x33, 0x4c,
	0x62, 0xcb, 0x6c, 0x09, 0x08, 0x01, 0x99, 0x0b, 0x11, 0xae, 0xc4, 0x44, 0x4d, 0x5e, 0x82, 0x3a,
	0x8b, 0xa6, 0xf3, 0x61, 0x94, 0x86, 0x2a, 0x18, 0x7d, 0x21, 0x3b, 0x12, 0x4b, 0x1b, 0xe4, 0x7f,
	0x90, 0x5d, 0x7f, 0x3e, 0x49, 0x03, 0x29, 0x86, 0xe9, 0xcf, 0x27, 0x1d, 0x89, 0x09, 0x48, 0xb6,
	0xa0, 0xe4, 0xf9, 0x91, 0x3b, 0x1d, 0x71, 0x47, 0x45, 0x4c, 0x80, 0x61, 0x2d, 0x08, 0x5f, 0x52,
	0xd6, 0xce, 0x52, 0xd7, 0x40, 0x4d, 0x4c, 0x08, 0x05, 0x75, 0xe4, 0xb9, 0xe3, 0xf3, 0x59, 0x25,
	0x5f, 0xcd, 0xd7, 0xb4, 0xba, 0x6a, 0xec, 0x71, 0xc9, 0x52, 0xaa, 0xbf, 0x07, 0x45, 0x80, 0x2c,
	0x3a, 0x7a, 0x10, 0x7d, 0x03, 0xe4, 0x6c, 0xd7, 0x0f, 0x16, 0xc5, 0x04, 0xd5, 0x37, 0x41, 0xe6,
	0x41, 0xb9, 0xc5, 0xa5, 0x33, 0x9e, 0xbb, 0x4b, 0x8b, 0x23, 0x2e, 0x59, 0x4a, 0xf5, 0x77, 0xa0,
	0x08, 0xf0, 0xac, 0xc5, 0x7f, 0xa0, 0x88, 0x31, 0xe1, 0xb1, 0xce, 0x12, 0xa1, 0xbf, 0x85, 0x52,
	0x76, 0x43, 0xa2, 0x43, 0xd9, 0xe3, 0x3f, 0xc0, 0xc4, 0xe5, 0x68, 0x56, 0x41, 0xd5, 0x7c, 0x4d,
	0x66, 0x8f, 0x98, 0xfe, 0x09, 0xd4, 0x03, 0x37, 0xba, 0x08, 0xce, 0xc9, 0x8b, 0x34, 0x73, 0xf2,
	0xa4, 0x34, 0x23, 0xc1, 0x22, 0xb9, 0x68, 0x10, 0x0a, 0x8a, 0xe7, 0x87, 0xf3, 0xe8, 0xc9, 0xad,
	0x12, 0x4c, 0xaa, 0xa0, 0x06, 0xf3, 0x88, 0x0f, 0xfc, 0xf3, 0x88, 0x58, 0xca, 0xf5, 0xd7, 0xa0,
	0xd8, 0xce, 0xd9, 0x78, 0xb9, 0x1f, 0xf4, 0xdc, 0x7e, 0xb6, 0xfe, 0x20, 0x58, 0x79, 0xf4, 0xa0,
	0x49, 0x11, 0xe4, 0xf6, 0xe1, 0x61, 0x17, 0x4b, 0xbc, 0xb2, 0x7a, 0xf6, 0x36, 0x46, 0xa4, 0x04,
	0x8a, 0xd5, 0xb3, 0x9b, 0x0d, 0x9c, 0x23, 0x00, 0xea, 0x80, 0xd3, 0x3a, 0xce, 0x2f, 0xea, 0x66,
	0x03, 0xcb, 0xbc, 0xee, 0x27, 0x5c, 0x59, 0xd4, 0xcd, 0x06, 0x56, 0x89, 0x06, 0x85, 0x3d, 0xeb,
	0xd8, 0xdc, 0xdd, 0xae, 0xe3, 0x42, 0x26, 0x9a, 0x0d, 0x5c, 0x24, 0x65, 0x28, 0xf6, 0x17, 0xad,
	0xd2, 0x52, 0x35, 0x1b, 0x18, 0xc4, 0x09, 0x36, 0xb3, 0x7a, 0xfb, 0x58, 0xe3, 0xe6, 0xed, 0x13,
	0xdb, 0xec, 0xe3, 0x32, 0x59, 0x03, 0xad, 0x6d, 0xed, 0x9f, 0x5a, 0x3d, 0xdb, 0xdc, 0x37, 0x19,
	0x5e, 0x59, 0x80, 0x5d, 0x73, 0xc7, 0x3a, 0x68, 0x75, 0xf1, 0x2a, 0x3f, 0x66, 0xb7, 0x65, 0x9b,
	0xb6, 0x75, 0x60, 0xe2, 0x35, 0xa1, 0x06, 0xac, 0x65, 0x5b, 0x87, 0x3d, 0x8c, 0xb9, 0xe2, 0x5f,
	0xb2, 0xa3, 0x56, 0x17, 0xaf, 0x6f, 0xbd, 0x01, 0x58, 0xae, 0x9d, 0xa8, 0x90, 0xb3, 0x8f, 0xb1,
	0xc4, 0xcd, 0x3e, 0x0e, 0x4c, 0x76, 0x82, 0x11, 0xbf, 0xfe, 0xc0, 0xb6, 0xba, 0x38, 0xd7, 0x6e,
	0x5c, 0xdf, 0x52, 0xe9, 0xe6, 0x96, 0x4a, 0xf7, 0xb7, 0x14, 0x7d, 0x89, 0x29, 0xfa, 0x16, 0x53,
	0xf4, 0x33, 0xa6, 0xe8, 0x3a, 0xa6, 0xe8, 0x57, 0x4c, 0xd1, 0xef, 0x98, 0x4a, 0xf7, 0x31, 0x45,
	0x5f, 0xef, 0xa8, 0x74, 0x7d, 0x47, 0xa5, 0x9b, 0x3b, 0x2a, 0x9d, 0xa9, 0xe2, 0xff, 0x64, 0xfb,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xab, 0x95, 0xbb, 0x65, 0x04, 0x00, 0x00,
}

func (x PrimitiveType) String() string {
	s, ok := PrimitiveType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x MethodType) String() string {
	s, ok := MethodType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *TypeRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TypeRef)
	if !ok {
		that2, ok := that.(TypeRef)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.Info == nil {
		if this.Info != nil {
			return false
		}
	} else if this.Info == nil {
		return false
	} else if !this.Info.Equal(that1.Info) {
		return false
	}
	return true
}
func (this *TypeRef_Primitive) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TypeRef_Primitive)
	if !ok {
		that2, ok := that.(TypeRef_Primitive)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Primitive != that1.Primitive {
		return false
	}
	return true
}
func (this *TypeRef_ComplexType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TypeRef_ComplexType)
	if !ok {
		that2, ok := that.(TypeRef_ComplexType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ComplexType != that1.ComplexType {
		return false
	}
	return true
}
func (this *TypeRef_Array) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TypeRef_Array)
	if !ok {
		that2, ok := that.(TypeRef_Array)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Array.Equal(that1.Array) {
		return false
	}
	return true
}
func (this *TypeRef_Optional) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TypeRef_Optional)
	if !ok {
		that2, ok := that.(TypeRef_Optional)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Optional.Equal(that1.Optional) {
		return false
	}
	return true
}
func (this *ComplexType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ComplexType)
	if !ok {
		that2, ok := that.(ComplexType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Namespace != that1.Namespace {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if that1.Info == nil {
		if this.Info != nil {
			return false
		}
	} else if this.Info == nil {
		return false
	} else if !this.Info.Equal(that1.Info) {
		return false
	}
	return true
}
func (this *ComplexType_Struct) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ComplexType_Struct)
	if !ok {
		that2, ok := that.(ComplexType_Struct)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Struct.Equal(that1.Struct) {
		return false
	}
	return true
}
func (this *ComplexType_Enum) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ComplexType_Enum)
	if !ok {
		that2, ok := that.(ComplexType_Enum)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Enum.Equal(that1.Enum) {
		return false
	}
	return true
}
func (this *ComplexType_Interface) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ComplexType_Interface)
	if !ok {
		that2, ok := that.(ComplexType_Interface)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Interface.Equal(that1.Interface) {
		return false
	}
	return true
}
func (this *Struct) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Struct)
	if !ok {
		that2, ok := that.(Struct)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Fields) != len(that1.Fields) {
		return false
	}
	for i := range this.Fields {
		if !this.Fields[i].Equal(that1.Fields[i]) {
			return false
		}
	}
	return true
}
func (this *Field) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Field)
	if !ok {
		that2, ok := that.(Field)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if !this.Type.Equal(that1.Type) {
		return false
	}
	return true
}
func (this *Enum) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Enum)
	if !ok {
		that2, ok := that.(Enum)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Values) != len(that1.Values) {
		return false
	}
	for i := range this.Values {
		if !this.Values[i].Equal(that1.Values[i]) {
			return false
		}
	}
	return true
}
func (this *Value) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Value)
	if !ok {
		that2, ok := that.(Value)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (this *Interface) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Interface)
	if !ok {
		that2, ok := that.(Interface)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Implementers) != len(that1.Implementers) {
		return false
	}
	for i := range this.Implementers {
		if this.Implementers[i] != that1.Implementers[i] {
			return false
		}
	}
	return true
}
func (this *Method) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Method)
	if !ok {
		that2, ok := that.(Method)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if !this.Input.Equal(that1.Input) {
		return false
	}
	if !this.Output.Equal(that1.Output) {
		return false
	}
	return true
}
func (this *Table) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Table)
	if !ok {
		that2, ok := that.(Table)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Type.Equal(that1.Type) {
		return false
	}
	return true
}
func (this *TypeRef) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&chain_schema.TypeRef{")
	if this.Info != nil {
		s = append(s, "Info: "+fmt.Sprintf("%#v", this.Info)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TypeRef_Primitive) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&chain_schema.TypeRef_Primitive{` +
		`Primitive:` + fmt.Sprintf("%#v", this.Primitive) + `}`}, ", ")
	return s
}
func (this *TypeRef_ComplexType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&chain_schema.TypeRef_ComplexType{` +
		`ComplexType:` + fmt.Sprintf("%#v", this.ComplexType) + `}`}, ", ")
	return s
}
func (this *TypeRef_Array) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&chain_schema.TypeRef_Array{` +
		`Array:` + fmt.Sprintf("%#v", this.Array) + `}`}, ", ")
	return s
}
func (this *TypeRef_Optional) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&chain_schema.TypeRef_Optional{` +
		`Optional:` + fmt.Sprintf("%#v", this.Optional) + `}`}, ", ")
	return s
}
func (this *ComplexType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&chain_schema.ComplexType{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	if this.Info != nil {
		s = append(s, "Info: "+fmt.Sprintf("%#v", this.Info)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ComplexType_Struct) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&chain_schema.ComplexType_Struct{` +
		`Struct:` + fmt.Sprintf("%#v", this.Struct) + `}`}, ", ")
	return s
}
func (this *ComplexType_Enum) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&chain_schema.ComplexType_Enum{` +
		`Enum:` + fmt.Sprintf("%#v", this.Enum) + `}`}, ", ")
	return s
}
func (this *ComplexType_Interface) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&chain_schema.ComplexType_Interface{` +
		`Interface:` + fmt.Sprintf("%#v", this.Interface) + `}`}, ", ")
	return s
}
func (this *Struct) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&chain_schema.Struct{")
	if this.Fields != nil {
		s = append(s, "Fields: "+fmt.Sprintf("%#v", this.Fields)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Field) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&chain_schema.Field{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	if this.Type != nil {
		s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Enum) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&chain_schema.Enum{")
	if this.Values != nil {
		s = append(s, "Values: "+fmt.Sprintf("%#v", this.Values)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Value) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&chain_schema.Value{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Interface) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&chain_schema.Interface{")
	s = append(s, "Implementers: "+fmt.Sprintf("%#v", this.Implementers)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Method) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&chain_schema.Method{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	if this.Input != nil {
		s = append(s, "Input: "+fmt.Sprintf("%#v", this.Input)+",\n")
	}
	if this.Output != nil {
		s = append(s, "Output: "+fmt.Sprintf("%#v", this.Output)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Table) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&chain_schema.Table{")
	if this.Type != nil {
		s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringChainSchema(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TypeRef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TypeRef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TypeRef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Info != nil {
		{
			size := m.Info.Size()
			i -= size
			if _, err := m.Info.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *TypeRef_Primitive) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TypeRef_Primitive) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintChainSchema(dAtA, i, uint64(m.Primitive))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}
func (m *TypeRef_ComplexType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TypeRef_ComplexType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintChainSchema(dAtA, i, uint64(m.ComplexType))
	i--
	dAtA[i] = 0x10
	return len(dAtA) - i, nil
}
func (m *TypeRef_Array) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TypeRef_Array) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Array != nil {
		{
			size, err := m.Array.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *TypeRef_Optional) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TypeRef_Optional) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Optional != nil {
		{
			size, err := m.Optional.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *ComplexType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ComplexType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ComplexType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Info != nil {
		{
			size := m.Info.Size()
			i -= size
			if _, err := m.Info.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintChainSchema(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Namespace != 0 {
		i = encodeVarintChainSchema(dAtA, i, uint64(m.Namespace))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ComplexType_Struct) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ComplexType_Struct) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Struct != nil {
		{
			size, err := m.Struct.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *ComplexType_Enum) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ComplexType_Enum) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Enum != nil {
		{
			size, err := m.Enum.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *ComplexType_Interface) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ComplexType_Interface) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Interface != nil {
		{
			size, err := m.Interface.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *Struct) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Struct) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Struct) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fields) > 0 {
		for iNdEx := len(m.Fields) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fields[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintChainSchema(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	return len(dAtA) - i, nil
}

func (m *Field) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Field) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Field) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != nil {
		{
			size, err := m.Type.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintChainSchema(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Enum) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Enum) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Enum) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Values) > 0 {
		for iNdEx := len(m.Values) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Values[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintChainSchema(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	return len(dAtA) - i, nil
}

func (m *Value) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Value) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Value) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintChainSchema(dAtA, i, uint64((uint32(m.Value)<<1)^uint32((m.Value>>31))))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintChainSchema(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Interface) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Interface) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Interface) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Implementers) > 0 {
		dAtA8 := make([]byte, len(m.Implementers)*10)
		var j7 int
		for _, num := range m.Implementers {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintChainSchema(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Method) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Method) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Method) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Output != nil {
		{
			size, err := m.Output.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Input != nil {
		{
			size, err := m.Input.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintChainSchema(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Table) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Table) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Table) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != nil {
		{
			size, err := m.Type.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainSchema(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintChainSchema(dAtA []byte, offset int, v uint64) int {
	offset -= sovChainSchema(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TypeRef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Info != nil {
		n += m.Info.Size()
	}
	return n
}

func (m *TypeRef_Primitive) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovChainSchema(uint64(m.Primitive))
	return n
}
func (m *TypeRef_ComplexType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovChainSchema(uint64(m.ComplexType))
	return n
}
func (m *TypeRef_Array) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Array != nil {
		l = m.Array.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}
func (m *TypeRef_Optional) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Optional != nil {
		l = m.Optional.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}
func (m *ComplexType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Namespace != 0 {
		n += 1 + sovChainSchema(uint64(m.Namespace))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovChainSchema(uint64(l))
	}
	if m.Info != nil {
		n += m.Info.Size()
	}
	return n
}

func (m *ComplexType_Struct) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Struct != nil {
		l = m.Struct.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}
func (m *ComplexType_Enum) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enum != nil {
		l = m.Enum.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}
func (m *ComplexType_Interface) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Interface != nil {
		l = m.Interface.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}
func (m *Struct) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fields) > 0 {
		for _, e := range m.Fields {
			l = e.Size()
			n += 1 + l + sovChainSchema(uint64(l))
		}
	}
	return n
}

func (m *Field) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovChainSchema(uint64(l))
	}
	if m.Type != nil {
		l = m.Type.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}

func (m *Enum) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Values) > 0 {
		for _, e := range m.Values {
			l = e.Size()
			n += 1 + l + sovChainSchema(uint64(l))
		}
	}
	return n
}

func (m *Value) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovChainSchema(uint64(l))
	}
	if m.Value != 0 {
		n += 1 + sozChainSchema(uint64(m.Value))
	}
	return n
}

func (m *Interface) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Implementers) > 0 {
		l = 0
		for _, e := range m.Implementers {
			l += sovChainSchema(uint64(e))
		}
		n += 1 + sovChainSchema(uint64(l)) + l
	}
	return n
}

func (m *Method) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovChainSchema(uint64(m.Type))
	}
	if m.Input != nil {
		l = m.Input.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	if m.Output != nil {
		l = m.Output.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}

func (m *Table) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != nil {
		l = m.Type.Size()
		n += 1 + l + sovChainSchema(uint64(l))
	}
	return n
}

func sovChainSchema(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChainSchema(x uint64) (n int) {
	return sovChainSchema(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TypeRef) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TypeRef{`,
		`Info:` + fmt.Sprintf("%v", this.Info) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TypeRef_Primitive) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TypeRef_Primitive{`,
		`Primitive:` + fmt.Sprintf("%v", this.Primitive) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TypeRef_ComplexType) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TypeRef_ComplexType{`,
		`ComplexType:` + fmt.Sprintf("%v", this.ComplexType) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TypeRef_Array) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TypeRef_Array{`,
		`Array:` + strings.Replace(fmt.Sprintf("%v", this.Array), "TypeRef", "TypeRef", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TypeRef_Optional) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TypeRef_Optional{`,
		`Optional:` + strings.Replace(fmt.Sprintf("%v", this.Optional), "TypeRef", "TypeRef", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ComplexType) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ComplexType{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Info:` + fmt.Sprintf("%v", this.Info) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ComplexType_Struct) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ComplexType_Struct{`,
		`Struct:` + strings.Replace(fmt.Sprintf("%v", this.Struct), "Struct", "Struct", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ComplexType_Enum) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ComplexType_Enum{`,
		`Enum:` + strings.Replace(fmt.Sprintf("%v", this.Enum), "Enum", "Enum", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ComplexType_Interface) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ComplexType_Interface{`,
		`Interface:` + strings.Replace(fmt.Sprintf("%v", this.Interface), "Interface", "Interface", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Struct) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForFields := "[]*Field{"
	for _, f := range this.Fields {
		repeatedStringForFields += strings.Replace(f.String(), "Field", "Field", 1) + ","
	}
	repeatedStringForFields += "}"
	s := strings.Join([]string{`&Struct{`,
		`Fields:` + repeatedStringForFields + `,`,
		`}`,
	}, "")
	return s
}
func (this *Field) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Field{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Type:` + strings.Replace(this.Type.String(), "TypeRef", "TypeRef", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Enum) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForValues := "[]*Value{"
	for _, f := range this.Values {
		repeatedStringForValues += strings.Replace(f.String(), "Value", "Value", 1) + ","
	}
	repeatedStringForValues += "}"
	s := strings.Join([]string{`&Enum{`,
		`Values:` + repeatedStringForValues + `,`,
		`}`,
	}, "")
	return s
}
func (this *Value) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Value{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Interface) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Interface{`,
		`Implementers:` + fmt.Sprintf("%v", this.Implementers) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Method) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Method{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Input:` + strings.Replace(this.Input.String(), "TypeRef", "TypeRef", 1) + `,`,
		`Output:` + strings.Replace(this.Output.String(), "TypeRef", "TypeRef", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Table) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Table{`,
		`Type:` + strings.Replace(this.Type.String(), "TypeRef", "TypeRef", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringChainSchema(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TypeRef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TypeRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TypeRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Primitive", wireType)
			}
			var v PrimitiveType
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= PrimitiveType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Info = &TypeRef_Primitive{v}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ComplexType", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Info = &TypeRef_ComplexType{v}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Array", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TypeRef{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Info = &TypeRef_Array{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Optional", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TypeRef{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Info = &TypeRef_Optional{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ComplexType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ComplexType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ComplexType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			m.Namespace = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Namespace |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Struct", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Struct{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Info = &ComplexType_Struct{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enum", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Enum{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Info = &ComplexType_Enum{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interface", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Interface{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Info = &ComplexType_Interface{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Struct) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Struct: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Struct: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fields = append(m.Fields, &Field{})
			if err := m.Fields[len(m.Fields)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Field) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Field: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Field: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Type == nil {
				m.Type = &TypeRef{}
			}
			if err := m.Type.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Enum) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Enum: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Enum: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Values = append(m.Values, &Value{})
			if err := m.Values[len(m.Values)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Value) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Value: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Value: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Value = v
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Interface) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Interface: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Interface: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowChainSchema
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Implementers = append(m.Implementers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowChainSchema
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthChainSchema
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthChainSchema
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Implementers) == 0 {
					m.Implementers = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowChainSchema
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Implementers = append(m.Implementers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Implementers", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Method) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Method: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Method: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= MethodType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Input == nil {
				m.Input = &TypeRef{}
			}
			if err := m.Input.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Output == nil {
				m.Output = &TypeRef{}
			}
			if err := m.Output.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Table) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Table: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Table: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Type == nil {
				m.Type = &TypeRef{}
			}
			if err := m.Type.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChainSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChainSchema(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChainSchema
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainSchema
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChainSchema
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChainSchema
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChainSchema
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChainSchema        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChainSchema          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChainSchema = fmt.Errorf("proto: unexpected end of group")
)
